# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://easymap.land.moi.gov.tw/R02/Index")
    self.driver.set_window_size(1111, 706)
    
    self.driver.find_element(By.ID, "button_addr").click()

    self.driver.find_element(By.ID, "select_city_id1").click()
    dropdown = self.driver.find_element(By.ID, "select_city_id1")
    dropdown.find_element(By.XPATH, "//option[. = '臺中市']").click()

    self.driver.find_element(By.ID, "select_city_id1").click()
    element = self.driver.find_element(By.ID, "select_town_id1")

    
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.close()
  
